// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: emidev98/cosmwasmlifecycle/contract.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Contract defines the parameters for the module.
type Contract struct {
	// Contract's execution type
	ExecutionType ExecutionType `protobuf:"varint,1,opt,name=execution_type,json=executionType,proto3,enum=emidev98.cosmwasmlifecycle.ExecutionType" json:"execution_type,omitempty"`
	// Execution frequency
	ExecutionFrequency int64 `protobuf:"varint,2,opt,name=execution_frequency,json=executionFrequency,proto3" json:"execution_frequency,omitempty"`
	// Latest block execution
	LatestBlockExecution int64 `protobuf:"varint,3,opt,name=latest_block_execution,json=latestBlockExecution,proto3" json:"latest_block_execution,omitempty"`
	// Amount of strikes that the contract has at the moment.
	Strikes int64 `protobuf:"varint,4,opt,name=strikes,proto3" json:"strikes,omitempty"`
	// Collateral deposited to the contract.
	Deposit github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=deposit,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"deposit"`
}

func (m *Contract) Reset()         { *m = Contract{} }
func (m *Contract) String() string { return proto.CompactTextString(m) }
func (*Contract) ProtoMessage()    {}
func (*Contract) Descriptor() ([]byte, []int) {
	return fileDescriptor_aaa869d087db789f, []int{0}
}
func (m *Contract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Contract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Contract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Contract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contract.Merge(m, src)
}
func (m *Contract) XXX_Size() int {
	return m.Size()
}
func (m *Contract) XXX_DiscardUnknown() {
	xxx_messageInfo_Contract.DiscardUnknown(m)
}

var xxx_messageInfo_Contract proto.InternalMessageInfo

func (m *Contract) GetExecutionType() ExecutionType {
	if m != nil {
		return m.ExecutionType
	}
	return ExecutionType_BEGIN_BLOCK
}

func (m *Contract) GetExecutionFrequency() int64 {
	if m != nil {
		return m.ExecutionFrequency
	}
	return 0
}

func (m *Contract) GetLatestBlockExecution() int64 {
	if m != nil {
		return m.LatestBlockExecution
	}
	return 0
}

func (m *Contract) GetStrikes() int64 {
	if m != nil {
		return m.Strikes
	}
	return 0
}

func init() {
	proto.RegisterType((*Contract)(nil), "emidev98.cosmwasmlifecycle.Contract")
}

func init() {
	proto.RegisterFile("emidev98/cosmwasmlifecycle/contract.proto", fileDescriptor_aaa869d087db789f)
}

var fileDescriptor_aaa869d087db789f = []byte{
	// 366 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x51, 0xc1, 0x4e, 0xea, 0x40,
	0x14, 0x6d, 0xe1, 0xbd, 0xc7, 0x4b, 0x8d, 0x2c, 0x2a, 0x31, 0x85, 0x45, 0x21, 0x6e, 0x84, 0x05,
	0x33, 0x01, 0x5d, 0xe8, 0xce, 0x40, 0x74, 0x6d, 0x88, 0x2b, 0x36, 0x4d, 0x3b, 0xbd, 0xe0, 0x84,
	0xb6, 0x53, 0x3b, 0x03, 0xd2, 0xbf, 0xf0, 0x9f, 0xdc, 0xb0, 0x64, 0x69, 0x5c, 0x10, 0x03, 0x3f,
	0x62, 0xda, 0x4e, 0x01, 0x83, 0xba, 0x6a, 0x4f, 0xce, 0x39, 0xf7, 0xde, 0x39, 0x47, 0x6b, 0x81,
	0x4f, 0x5d, 0x98, 0x5d, 0x5f, 0x61, 0xc2, 0xb8, 0xff, 0x6c, 0x73, 0xdf, 0xa3, 0x23, 0x20, 0x31,
	0xf1, 0x00, 0x13, 0x16, 0x88, 0xc8, 0x26, 0x02, 0x85, 0x11, 0x13, 0x4c, 0xaf, 0xe5, 0x52, 0x74,
	0x20, 0xad, 0x55, 0xc6, 0x6c, 0xcc, 0x52, 0x19, 0x4e, 0xfe, 0x32, 0x47, 0xad, 0x9a, 0x08, 0x19,
	0xb7, 0x32, 0x22, 0x03, 0x92, 0x32, 0x33, 0x84, 0x1d, 0x9b, 0x03, 0x9e, 0x75, 0x1c, 0x10, 0x76,
	0x07, 0x13, 0x46, 0x03, 0xc9, 0xe3, 0x5f, 0xee, 0x82, 0x39, 0x90, 0xa9, 0xa0, 0x2c, 0xb0, 0x44,
	0x1c, 0x42, 0x66, 0x38, 0x7b, 0x2d, 0x68, 0xff, 0xfb, 0xf2, 0x60, 0xfd, 0x5e, 0x2b, 0x7f, 0x15,
	0x19, 0x6a, 0x43, 0x6d, 0x96, 0xbb, 0x2d, 0xf4, 0xf3, 0x1b, 0xd0, 0x6d, 0xee, 0x78, 0x88, 0x43,
	0x18, 0x1c, 0xc3, 0x3e, 0xd4, 0xb1, 0x76, 0xb2, 0x9b, 0x38, 0x8a, 0xe0, 0x69, 0x0a, 0x01, 0x89,
	0x8d, 0x42, 0x43, 0x6d, 0x16, 0x07, 0xfa, 0x96, 0xba, 0xcb, 0x19, 0xfd, 0x52, 0x3b, 0xf5, 0x6c,
	0x01, 0x5c, 0x58, 0x8e, 0xc7, 0xc8, 0xc4, 0xda, 0x4a, 0x8c, 0x62, 0xea, 0xa9, 0x64, 0x6c, 0x2f,
	0x21, 0xb7, 0x9b, 0x75, 0x43, 0x2b, 0x71, 0x11, 0xd1, 0x09, 0x70, 0xe3, 0x4f, 0x2a, 0xcb, 0xa1,
	0xee, 0x6a, 0x25, 0x17, 0x42, 0xc6, 0xa9, 0x30, 0xfe, 0x36, 0xd4, 0xe6, 0x51, 0xb7, 0x8a, 0x64,
	0xa0, 0x49, 0x84, 0x48, 0x46, 0x88, 0xfa, 0x8c, 0x06, 0x3d, 0xbc, 0x58, 0xd5, 0x95, 0xf7, 0x55,
	0xfd, 0x7c, 0x4c, 0xc5, 0xe3, 0xd4, 0x41, 0x84, 0xf9, 0x32, 0x7d, 0xf9, 0x69, 0x73, 0x77, 0x82,
	0x93, 0x5c, 0x78, 0x6a, 0x18, 0xe4, 0xa3, 0x7b, 0xc3, 0xc5, 0xda, 0x54, 0x97, 0x6b, 0x53, 0xfd,
	0x58, 0x9b, 0xea, 0xcb, 0xc6, 0x54, 0x96, 0x1b, 0x53, 0x79, 0xdb, 0x98, 0xca, 0xf0, 0x66, 0x6f,
	0xd6, 0x41, 0x37, 0xed, 0x5d, 0x39, 0xf3, 0x6f, 0x0a, 0x4b, 0x37, 0x39, 0xff, 0xd2, 0xa2, 0x2e,
	0x3e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xcc, 0xd9, 0x03, 0x9a, 0x73, 0x02, 0x00, 0x00,
}

func (m *Contract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Contract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Contract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Deposit.Size()
		i -= size
		if _, err := m.Deposit.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintContract(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.Strikes != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.Strikes))
		i--
		dAtA[i] = 0x20
	}
	if m.LatestBlockExecution != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.LatestBlockExecution))
		i--
		dAtA[i] = 0x18
	}
	if m.ExecutionFrequency != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.ExecutionFrequency))
		i--
		dAtA[i] = 0x10
	}
	if m.ExecutionType != 0 {
		i = encodeVarintContract(dAtA, i, uint64(m.ExecutionType))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintContract(dAtA []byte, offset int, v uint64) int {
	offset -= sovContract(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Contract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ExecutionType != 0 {
		n += 1 + sovContract(uint64(m.ExecutionType))
	}
	if m.ExecutionFrequency != 0 {
		n += 1 + sovContract(uint64(m.ExecutionFrequency))
	}
	if m.LatestBlockExecution != 0 {
		n += 1 + sovContract(uint64(m.LatestBlockExecution))
	}
	if m.Strikes != 0 {
		n += 1 + sovContract(uint64(m.Strikes))
	}
	l = m.Deposit.Size()
	n += 1 + l + sovContract(uint64(l))
	return n
}

func sovContract(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozContract(x uint64) (n int) {
	return sovContract(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Contract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowContract
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Contract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Contract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionType", wireType)
			}
			m.ExecutionType = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutionType |= ExecutionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExecutionFrequency", wireType)
			}
			m.ExecutionFrequency = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExecutionFrequency |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestBlockExecution", wireType)
			}
			m.LatestBlockExecution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LatestBlockExecution |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Strikes", wireType)
			}
			m.Strikes = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Strikes |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowContract
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthContract
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthContract
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Deposit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipContract(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthContract
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipContract(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowContract
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowContract
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthContract
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupContract
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthContract
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthContract        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowContract          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupContract = fmt.Errorf("proto: unexpected end of group")
)
