// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cosmwasmlifecycle/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ExecutionType int32

const (
	ExecutionType_BEGIN_BLOCK ExecutionType = 0
	ExecutionType_END_BLOCK   ExecutionType = 1
)

var ExecutionType_name = map[int32]string{
	0: "BEGIN_BLOCK",
	1: "END_BLOCK",
}

var ExecutionType_value = map[string]int32{
	"BEGIN_BLOCK": 0,
	"END_BLOCK":   1,
}

func (x ExecutionType) String() string {
	return proto.EnumName(ExecutionType_name, int32(x))
}

func (ExecutionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_5a8c9d0c2a02a50a, []int{0}
}

type MsgEnableBlockExecution struct {
	ContractAddress string        `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Execution       ExecutionType `protobuf:"varint,2,opt,name=execution,proto3,enum=cosmwasmlifecycle.ExecutionType" json:"execution,omitempty"`
}

func (m *MsgEnableBlockExecution) Reset()         { *m = MsgEnableBlockExecution{} }
func (m *MsgEnableBlockExecution) String() string { return proto.CompactTextString(m) }
func (*MsgEnableBlockExecution) ProtoMessage()    {}
func (*MsgEnableBlockExecution) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a8c9d0c2a02a50a, []int{0}
}
func (m *MsgEnableBlockExecution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnableBlockExecution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnableBlockExecution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnableBlockExecution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnableBlockExecution.Merge(m, src)
}
func (m *MsgEnableBlockExecution) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnableBlockExecution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnableBlockExecution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnableBlockExecution proto.InternalMessageInfo

type MsgEnableBlockExecutionResponse struct {
}

func (m *MsgEnableBlockExecutionResponse) Reset()         { *m = MsgEnableBlockExecutionResponse{} }
func (m *MsgEnableBlockExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgEnableBlockExecutionResponse) ProtoMessage()    {}
func (*MsgEnableBlockExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a8c9d0c2a02a50a, []int{1}
}
func (m *MsgEnableBlockExecutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgEnableBlockExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgEnableBlockExecutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgEnableBlockExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgEnableBlockExecutionResponse.Merge(m, src)
}
func (m *MsgEnableBlockExecutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgEnableBlockExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgEnableBlockExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgEnableBlockExecutionResponse proto.InternalMessageInfo

type MsgDisableBlockExecution struct {
	ContractAddress string        `protobuf:"bytes,1,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	Execution       ExecutionType `protobuf:"varint,2,opt,name=execution,proto3,enum=cosmwasmlifecycle.ExecutionType" json:"execution,omitempty"`
}

func (m *MsgDisableBlockExecution) Reset()         { *m = MsgDisableBlockExecution{} }
func (m *MsgDisableBlockExecution) String() string { return proto.CompactTextString(m) }
func (*MsgDisableBlockExecution) ProtoMessage()    {}
func (*MsgDisableBlockExecution) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a8c9d0c2a02a50a, []int{2}
}
func (m *MsgDisableBlockExecution) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableBlockExecution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableBlockExecution.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableBlockExecution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableBlockExecution.Merge(m, src)
}
func (m *MsgDisableBlockExecution) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableBlockExecution) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableBlockExecution.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableBlockExecution proto.InternalMessageInfo

type MsgDisableBlockExecutionResponse struct {
}

func (m *MsgDisableBlockExecutionResponse) Reset()         { *m = MsgDisableBlockExecutionResponse{} }
func (m *MsgDisableBlockExecutionResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDisableBlockExecutionResponse) ProtoMessage()    {}
func (*MsgDisableBlockExecutionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5a8c9d0c2a02a50a, []int{3}
}
func (m *MsgDisableBlockExecutionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDisableBlockExecutionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDisableBlockExecutionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDisableBlockExecutionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDisableBlockExecutionResponse.Merge(m, src)
}
func (m *MsgDisableBlockExecutionResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDisableBlockExecutionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDisableBlockExecutionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDisableBlockExecutionResponse proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("cosmwasmlifecycle.ExecutionType", ExecutionType_name, ExecutionType_value)
	proto.RegisterType((*MsgEnableBlockExecution)(nil), "cosmwasmlifecycle.MsgEnableBlockExecution")
	proto.RegisterType((*MsgEnableBlockExecutionResponse)(nil), "cosmwasmlifecycle.MsgEnableBlockExecutionResponse")
	proto.RegisterType((*MsgDisableBlockExecution)(nil), "cosmwasmlifecycle.MsgDisableBlockExecution")
	proto.RegisterType((*MsgDisableBlockExecutionResponse)(nil), "cosmwasmlifecycle.MsgDisableBlockExecutionResponse")
}

func init() { proto.RegisterFile("cosmwasmlifecycle/tx.proto", fileDescriptor_5a8c9d0c2a02a50a) }

var fileDescriptor_5a8c9d0c2a02a50a = []byte{
	// 389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4a, 0xce, 0x2f, 0xce,
	0x2d, 0x4f, 0x2c, 0xce, 0xcd, 0xc9, 0x4c, 0x4b, 0x4d, 0xae, 0x4c, 0xce, 0x49, 0xd5, 0x2f, 0xa9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc4, 0x90, 0x93, 0x12, 0x49, 0xcf, 0x4f, 0xcf,
	0x07, 0xcb, 0xea, 0x83, 0x58, 0x10, 0x85, 0x52, 0x92, 0x20, 0x85, 0xf9, 0xc5, 0xf1, 0x10, 0x09,
	0x08, 0x07, 0x22, 0xa5, 0xb4, 0x8e, 0x91, 0x4b, 0xdc, 0xb7, 0x38, 0xdd, 0x35, 0x2f, 0x31, 0x29,
	0x27, 0xd5, 0x29, 0x27, 0x3f, 0x39, 0xdb, 0xb5, 0x22, 0x35, 0xb9, 0xb4, 0x24, 0x33, 0x3f, 0x4f,
	0xc8, 0x99, 0x4b, 0x20, 0x39, 0x3f, 0xaf, 0xa4, 0x28, 0x31, 0xb9, 0x24, 0x3e, 0x31, 0x25, 0xa5,
	0x28, 0xb5, 0xb8, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83, 0xd3, 0x49, 0xe2, 0xd2, 0x16, 0x5d, 0x11,
	0xa8, 0x39, 0x8e, 0x10, 0x99, 0xe0, 0x92, 0xa2, 0xcc, 0xbc, 0xf4, 0x20, 0x7e, 0x98, 0x0e, 0xa8,
	0xb0, 0x90, 0x0b, 0x17, 0x67, 0x2a, 0xcc, 0x44, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x3e, 0x23, 0x05,
	0x3d, 0x0c, 0x87, 0xeb, 0xc1, 0x6d, 0x0d, 0xa9, 0x2c, 0x48, 0x75, 0x62, 0x39, 0x71, 0x4f, 0x9e,
	0x31, 0x08, 0xa1, 0xd1, 0x8a, 0xa3, 0x63, 0x81, 0x3c, 0xc3, 0x8b, 0x05, 0xf2, 0x0c, 0x4a, 0x8a,
	0x5c, 0xf2, 0x38, 0xdc, 0x1b, 0x94, 0x5a, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0xb4, 0x9e, 0x91,
	0x4b, 0xc2, 0xb7, 0x38, 0xdd, 0x25, 0xb3, 0x78, 0xa8, 0x78, 0x4a, 0x89, 0x4b, 0x01, 0x97, 0x83,
	0x61, 0xbe, 0xd2, 0xd2, 0xe7, 0xe2, 0x45, 0x31, 0x4f, 0x88, 0x9f, 0x8b, 0xdb, 0xc9, 0xd5, 0xdd,
	0xd3, 0x2f, 0xde, 0xc9, 0xc7, 0xdf, 0xd9, 0x5b, 0x80, 0x41, 0x88, 0x97, 0x8b, 0xd3, 0xd5, 0xcf,
	0x05, 0xca, 0x65, 0x34, 0xfa, 0xc1, 0xc8, 0xc5, 0xec, 0x5b, 0x9c, 0x2e, 0x54, 0xc6, 0x25, 0x82,
	0x35, 0x7a, 0xb5, 0xb0, 0xb8, 0x18, 0x47, 0xd0, 0x4a, 0x19, 0x11, 0xaf, 0x16, 0xe6, 0x60, 0xa1,
	0x4a, 0x2e, 0x51, 0xec, 0x51, 0xa0, 0x8d, 0xdd, 0x30, 0xac, 0x8a, 0xa5, 0x8c, 0x49, 0x50, 0x0c,
	0xb3, 0xda, 0x29, 0xea, 0xc4, 0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63,
	0x9c, 0xf0, 0x58, 0x8e, 0xe1, 0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x1c, 0xd2,
	0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x53, 0x73, 0x33, 0x53, 0x52, 0xcb,
	0x2c, 0x2d, 0xf4, 0x61, 0x36, 0xe8, 0x22, 0x32, 0x59, 0x85, 0x3e, 0x96, 0x8c, 0x57, 0x59, 0x90,
	0x5a, 0x9c, 0xc4, 0x06, 0xce, 0x38, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xf8, 0x8a,
	0x52, 0x9a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	EnableBlockExecution(ctx context.Context, in *MsgEnableBlockExecution, opts ...grpc.CallOption) (*MsgEnableBlockExecutionResponse, error)
	DisableBlockExecution(ctx context.Context, in *MsgDisableBlockExecution, opts ...grpc.CallOption) (*MsgDisableBlockExecutionResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) EnableBlockExecution(ctx context.Context, in *MsgEnableBlockExecution, opts ...grpc.CallOption) (*MsgEnableBlockExecutionResponse, error) {
	out := new(MsgEnableBlockExecutionResponse)
	err := c.cc.Invoke(ctx, "/cosmwasmlifecycle.Msg/EnableBlockExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DisableBlockExecution(ctx context.Context, in *MsgDisableBlockExecution, opts ...grpc.CallOption) (*MsgDisableBlockExecutionResponse, error) {
	out := new(MsgDisableBlockExecutionResponse)
	err := c.cc.Invoke(ctx, "/cosmwasmlifecycle.Msg/DisableBlockExecution", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	EnableBlockExecution(context.Context, *MsgEnableBlockExecution) (*MsgEnableBlockExecutionResponse, error)
	DisableBlockExecution(context.Context, *MsgDisableBlockExecution) (*MsgDisableBlockExecutionResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) EnableBlockExecution(ctx context.Context, req *MsgEnableBlockExecution) (*MsgEnableBlockExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableBlockExecution not implemented")
}
func (*UnimplementedMsgServer) DisableBlockExecution(ctx context.Context, req *MsgDisableBlockExecution) (*MsgDisableBlockExecutionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableBlockExecution not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_EnableBlockExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgEnableBlockExecution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).EnableBlockExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmwasmlifecycle.Msg/EnableBlockExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).EnableBlockExecution(ctx, req.(*MsgEnableBlockExecution))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DisableBlockExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDisableBlockExecution)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DisableBlockExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cosmwasmlifecycle.Msg/DisableBlockExecution",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DisableBlockExecution(ctx, req.(*MsgDisableBlockExecution))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cosmwasmlifecycle.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnableBlockExecution",
			Handler:    _Msg_EnableBlockExecution_Handler,
		},
		{
			MethodName: "DisableBlockExecution",
			Handler:    _Msg_DisableBlockExecution_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cosmwasmlifecycle/tx.proto",
}

func (m *MsgEnableBlockExecution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnableBlockExecution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnableBlockExecution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Execution != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Execution))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgEnableBlockExecutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgEnableBlockExecutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgEnableBlockExecutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDisableBlockExecution) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableBlockExecution) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableBlockExecution) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Execution != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Execution))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ContractAddress) > 0 {
		i -= len(m.ContractAddress)
		copy(dAtA[i:], m.ContractAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContractAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDisableBlockExecutionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDisableBlockExecutionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDisableBlockExecutionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgEnableBlockExecution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Execution != 0 {
		n += 1 + sovTx(uint64(m.Execution))
	}
	return n
}

func (m *MsgEnableBlockExecutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDisableBlockExecution) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ContractAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Execution != 0 {
		n += 1 + sovTx(uint64(m.Execution))
	}
	return n
}

func (m *MsgDisableBlockExecutionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgEnableBlockExecution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnableBlockExecution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnableBlockExecution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Execution", wireType)
			}
			m.Execution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Execution |= ExecutionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgEnableBlockExecutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgEnableBlockExecutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgEnableBlockExecutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableBlockExecution) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableBlockExecution: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableBlockExecution: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Execution", wireType)
			}
			m.Execution = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Execution |= ExecutionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDisableBlockExecutionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDisableBlockExecutionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDisableBlockExecutionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
